import Toric.Examples.CharCocharPairing
import Toric.Examples.SO2
import Toric.GroupScheme.Character
import Toric.GroupScheme.Diagonalizable
import Toric.GroupScheme.HopfAffine
import Toric.GroupScheme.MonoidAlgebra
import Toric.GroupScheme.Torus
import Toric.Hopf.Diagonalisable
import Toric.Hopf.GrpAlg
import Toric.Mathlib.Algebra.AffineMonoid.Embedding
import Toric.Mathlib.Algebra.AffineMonoid.Irreducible
import Toric.Mathlib.Algebra.AffineMonoid.UniqueSums
import Toric.Mathlib.Algebra.Category.CommHopfAlgCat
import Toric.Mathlib.Algebra.MonoidAlgebra.Basic
import Toric.Mathlib.Algebra.MonoidAlgebra.Module
import Toric.Mathlib.Algebra.Polynomial.Bivariate
import Toric.Mathlib.AlgebraicGeometry.Pullbacks
import Toric.Mathlib.RingTheory.AdjoinRoot
import Toric.Mathlib.RingTheory.Bialgebra.Convolution
import Toric.Mathlib.RingTheory.Bialgebra.GroupLike
import Toric.Mathlib.RingTheory.Bialgebra.MonoidAlgebra
import Toric.Mathlib.RingTheory.Bialgebra.TensorProduct
import Toric.Mathlib.RingTheory.Coalgebra.CoassocSimps
import Toric.Mathlib.RingTheory.Coalgebra.GroupLike
import Toric.Mathlib.RingTheory.Coalgebra.Hom
import Toric.Mathlib.RingTheory.Coalgebra.SimpAttr
import Toric.Mathlib.RingTheory.HopfAlgebra.Convolution
import Toric.Mathlib.RingTheory.HopfAlgebra.GroupLike
import Toric.Mathlib.RingTheory.HopfAlgebra.MonoidAlgebra
import Toric.Mathlib.RingTheory.TensorProduct.Maps
import Toric.MonoidAlgebra.TensorProduct
import Toric.MvLaurentPolynomial
import Toric.SphericalVariety
import Toric.ToricIdeal
import Toric.ToricVariety.Defs
import Toric.ToricVariety.FromMonoid
