/-
Copyright (c) 2025 Yaël Dillies. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yaël Dillies
-/
import Mathlib.GroupTheory.Finiteness
import Toric.Mathlib.Algebra.Group.Irreducible.Defs

/-!
# A salient affine monoid is generated by its irreducible elements
-/

variable {M : Type*} {S : Set M}

section AddCommMonoid
variable [AddCommMonoid M]

/-- Irreducible elements lie in all sets generating a salient monoid. -/
lemma addIrreducible_subset_of_addSubmonoidClosure_eq_top (hS : AddSubmonoid.closure S = ⊤) :
    {p | AddIrreducible p} ⊆ S := sorry

variable [AddMonoid.FG M]

/-- A finitely generated salient monoid has finitely many irreducible elements. -/
lemma finite_addIrreducible : {p : M | AddIrreducible p}.Finite := by
  obtain ⟨S, hS⟩ := ‹AddMonoid.FG M›
  exact S.finite_toSet.subset <| addIrreducible_subset_of_addSubmonoidClosure_eq_top hS

end AddCommMonoid

section AddCancelCommMonoid
variable [AddCancelCommMonoid M] [AddMonoid.FG M] [Subsingleton (AddUnits M)] {S : Set M}

@[simp] lemma AddSubmonoid.closure_addIrreducible :
    AddSubmonoid.closure {p : M | AddIrreducible p} = ⊤ := sorry

end AddCancelCommMonoid
